=== ScilifelabDataCentre/RDM-guidelines/schemas/data/checklist.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/schemas/data/checklist.schema.json",
  "title": "SciLifeLab RDM Guidelines Checklists",
  "description": "Schema for validating checklist objects used in the checklist topic pages",
  "type": "object",
  "required": ["title", "doi", "version", "items"],
  "properties": {
    "title": {
      "type": "string",
      "description": "Title of the checklist"
      
    },
    "doi": {
      "type": "string",
      "format": "uri",
      "description": "DOI of the checklist"
    },
    "version": {
      "type": "string",
      "description": "version of the checklist"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "title",
          "fair_category",
          "priority",
          "description",
          "explanation",
          "action",
          "project_size"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "description": "unique integer to differentiate items"
          },
          "title": {
            "type": "string",
            "description": "Short descriptor of checklist item"
          },
          "fair_category": {
            "type": "string",
            "description": "The letter of the FAIR acronym the item belongs to",
            "enum": ["", "F", "A", "I", "R"]
          },
          "priority": {
            "type": "integer",
            "enum": [1, 2, 3],
            "description": "How important it is the item is fulfilled. 1 is highest priority"
          },
          "description": {
            "type": "string",
            "description": "Longer descripton of checklist item. Markdown formatted"
          },
          "explanation": {
            "type": "string",
            "description": "Explanation of why checklist item is important. Markdown formatted"
          },
          "action": {
            "type": "string",
            "description": "How to fulfil the checklist item. Markdown formatted"
          },
          "project_size": {
            "type": "array",
            "description": "If the project has small or large scope.",
            "items": {
              "type": "string",
              "enum": ["small", "big"]
            },
            "minItems": 1,
            "uniqueItems": true
          }
        }
      }
    }
  }
}

=== ScilifelabDataCentre/RDM-guidelines/data/open_software_checklist.json
{
  "title": "SciLifeLab Open Software Checklist",
  "doi": "https://doi.org/10.17044/scilifelab.29086775.v2",
  "version": "v2",
  "items": [
    {
      "id": 0,
      "title": "Develop a Software Management Plan (SMP)",
      "fair_category": "",
      "priority": 1,
      "description": "Outline contributors, project name, versioning, coding standards, dependencies, testing, and sustainability. ",
      "explanation": "A Software Management Plan helps ensure that software is developed, maintained, and sustained in a planned and documented way.",
      "action": "Use the Software Sustainability Institute's [SMP guide and template](https://www.software.ac.uk/news/software-management-plans), Netherlands eScience Centers [Practical Guide to SMPs](https://zenodo.org/records/7589725) or the [Software Management Wizard (SMW)](https://smw.dsw.elixir-europe.org/wizard/) to create one.",
      "project_size": ["big"]
    },
    {
      "id": 1,
      "title": "Host Code in a Public Version-Controlled Repository",
      "fair_category": "A",
      "priority": 1,
      "description": "Host your code on platforms like GitHub, GitLab, or CodeBerg to track development history, enable tagged versioned releases, improve reusability, and support collaboration.",
      "explanation": "If your code isn't in a public repository that records version history, you can't see how it developed or which version produced certain results. It also makes it harder for others, or even your own team, to follow the process and work on the code together",
      "action": "Upload your code to a public version-controlled platform like GitHub.",
      "project_size": ["small", "big"]
    },
    {
      "id": 2,
      "title": "Choose an Open-Source Licence",
      "fair_category": "F",
      "priority": 1,
      "description": "Select an appropriate licence ([MIT License](https://choosealicense.com/licenses/mit/), [Apache License](https://choosealicense.com/licenses/apache-2.0/), or [GPL License](https://choosealicense.com/licenses/gpl-3.0/)), e.g., using [Choose a License](https://choosealicense.com/). If your repository also contains non-software content (e.g., website text or documentation), consider adding a separate licence for that, such as [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). Note that code or content without a licence can not legally be reused, even if it is publicly available.",
      "explanation": "If your code has no licence (that states how the code can be used, shared, or modified), it's not legally reusable, even if it is accessible.",
      "action": "Add a `LICENSE` file to your repository. Use a permissive licence such as the MIT Licence (SciLifeLab's standard) by either selecting **“Add file → Choose a license template”** on GitHub or copying the official licence legal text from its website and pasting it into your `LICENSE` file. If your repo includes other materials like text or figures, add a separate licence for those, for example, *CC BY 4.0* (4.0 is not available through GitHub so you need to copy and paste the legal text from [CC BY 4.0 legal text](https://creativecommons.org/licenses/by/4.0/legalcode.txt) into your LICENCE file). Name your code license LICENCE-CODE and your content licence LICENCE-CONTENT. If you mix different types (code, data, text), list each licence clearly in your `README` and specify what applies to what.",
      "project_size": ["small", "big"]
    },
    {
      "id": 3,
      "title": "Write a Structured README",
      "fair_category": "R",
      "priority": 1,
      "description": "Create a machine-readable `README.md` (e.g. using [readme.so](https://readme.so/)) with installation instructions, usage examples, required prerequisites, contribution guidelines, and licence information. Machine-readable means structured in a way that allows automated tools to identify and extract information, for the README for example by using plain text Markdown section titles.",
      "explanation": "Without a structured `README.md`, it is hard to understand what the code does, how to install or use it, or how to contribute. ",
      "action": "Add a `README.md` file to the repository. Include at least a title and description, and the sections 'Installation', 'Licence' and 'Citing this resource'. You can create the file by clicking pre-made sections in [readme.so](https://readme.so/) and filling in the relevant information.",
      "project_size": ["small", "big"]
    },
    {
      "id": 4,
      "title": "Archive and Assign a Persistent Identifier",
      "fair_category": "F",
      "priority": 1,
      "description": "Ensure long-term preservation by depositing a snapshot of a specific software release (e.g., v1.0.0) in repositories that assign a PID such as [Zenodo](https://zenodo.org/), [Software Heritage](https://www.softwareheritage.org/), or your local institutional repository (e.g., [SciLifeLab Data Repository](https://figshare.scilifelab.se/)). This complements hosting code in a public development repository by providing a fixed reference that can be cited in publications and matched to data and results.",
      "explanation": "Without a persistent identifier, references/links to the code may change or break over time. This makes citations unreliable and can prevent others from finding the code ( or correct version). Especially if the code is updated, renamed or moved.",
      "action": "Upload your code to Zenodo (by integrating Zenodo with your GitHub repository or by uploading manually) or another archive that gives it a DOI. Follow the steps to upload your code here: https://help.zenodo.org/docs/github/",
      "project_size": ["small", "big"]
    },
    {
      "id": 5,
      "title": "Provide Descriptive Metadata",
      "fair_category": "F",
      "priority": 1,
      "description": "Include essential details such as title, authors, version, licence, DOI and keywords. This can be done in a `CITATION.cff` file. For more extensive metadata, you can also create a `codemeta.json` file using tools like the [CodeMeta generator](https://codemeta.github.io/codemeta-generator/), which can then be added to public and preservation repositories (e.g. GitHub, Zenodo). One such file can be seen [here](https://github.com/cboettig/codemeta/blob/master/codemeta.json). Optionally, include a contributors table in your `README.md` (e.g., [The Turing Way's Contributors Table](https://book.the-turing-way.org/community-handbook/acknowledgement/acknowledgement-record)), or frameworks like [All Contributors](https://allcontributors.org/) to make roles and credit visible.",
      "explanation": "Without clear metadata, the code is harder to find, cite and connect to related research outputs. Missing author or licence information can also make attribution unclear.",
      "action": "Add a `CITATION.cff` file including title, authors, version, licence, (DOI, if available) and keywords.",
      "project_size": ["small", "big"]
    },
    {
      "id": 6,
      "title": "Use Package Managers and Manage Them Wisely",
      "fair_category": "I",
      "priority": 2,
      "description": "Specify dependencies via [package managers](https://en.wikipedia.org/wiki/List_of_software_package_management_systems) (e.g., pip, mamba) for better compatibility and reproducibility. Include a dependency file (e.g. `requirements.txt`, `environment.yml`) to allow others to easily install the necessary packages, and specify package versions to ensure the same versions are used across environments. Use well-maintained libraries and avoid obsolete and redundant dependencies so the software continues to work as intended over time.",
      "explanation": "Without a defined dependencies others can not easily use your code (and outdated packages may break the software or create security risks).",
      "action": "List all required dependencies in a file such as `requirements.txt` or `environment.yml` (this can be generated automatically with pipreqs, pip freeze or poetry). Preferably also specify version ranges (e.g. `wordfreq>=3.0,<4.0`).",
      "project_size": ["big"]
    },
    {
      "id": 7,
      "title": "Use Descriptive Names",
      "fair_category": "",
      "priority": 2,
      "description": "Choose consistent and descriptive names for variables, functions and files to make code easy to read and understand. See [The Turing Way Guidelines for Code Styling](https://book.the-turing-way.org/project-design/info-management/code-styling/code-styling-guidelines) ",
      "explanation": "Unclear or inconsistent naming makes the code harder to read, understand, and maintain. Both for you and for new users.",
      "action": "Use short but descriptive names that reflect what the variable or function does. Follow a consistent naming style (for example, `snake_case` in Python or `camelCase` in JavaScript) throughout the code.",
      "project_size": ["small", "big"]
    },
    {
      "id": 8,
      "title": "Write Clear Documentation ",
      "fair_category": "R",
      "priority": 2,
      "description": "Provide concise instructions, usage examples, and inline comments to help others understand and use the code. See [CodeRefinerys Modular Code Development lesson](https://cicero.xyz/v3/remark/0.14.0/github.com/coderefinery/modular-code-development/master/talk.md/#1) for more information.",
      "explanation": "If the documentation is incomplete or does not exist, or the code lacks comments showing how it should be used, others may be unable to understand or build upon the code. It also makes it harder for you and collaborators to maintain it later.",
      "action": "Add concise instructions and usage examples in your `README.md`, or for larger projects, create full documentation (e.g. a GitHub Pages or ReadTheDocs site). Write short, but informative, inline comments explaining what each part of the code does. Write docstrings for all functions and files. ",
      "project_size": ["small", "big"]
    },
    {
